### ISSUE TITLE
Gunner of a technical vehicle is undercover

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#157] opened 2017-11-10 11:21 UTC
**Version: develop
Mods: ACE
Mode: MP**

When retrieving a technical (camo pickup with mounted .50 cal gun), a car that is always "NOT UNDERCOVER", noticed that if you go to the gunner seat your are undercover

**Comment by LordGolias** [comment] 2017-11-12 07:14
I believe that this has been fixed in 70d445077f0d9a5080dc5e867749b3c8d3460202 since I cannot reproduce it.

Please re-open if it is not the case. :p

**Closed by LordGolias** 2017-11-12 07:14 UTC
Labels: bug, Done in develop
