### ISSUE TITLE
UPSMON .rpt spam

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#188] opened 2018-10-13 10:01 UTC
Iam getting a lot of .rpt spam with this error when I fly around Altis.
The full .rpt is attached as well.
It seems to happen when units are being spawned into the mission.

This started happening on the latest DEV branch. No units seem to be in the mission when the error rolls out.

```
11:57:35 Error in expression <_grpmission = "PATROL";

UPSMON_Total = UPSMON_Total + (count _members);


if (U>
11:57:35   Error position: <UPSMON_Total + (count _members);


if (U>
11:57:35   Error Undefined variable in expression: upsmon_total
11:57:35 File mpmissions\Antistasi.Altis\Scripts\UPSMON.sqf, line 97
```

**Comment by SomethingSimpl** [comment] 2018-10-13 10:02
Attached the .rpt
[Arma3_x64_2018-10-13_10-01-54.zip](https://github.com/LordGolias/antistasi/files/2475332/Arma3_x64_2018-10-13_10-01-54.zip)

**Comment by LordGolias** [comment] 2018-10-13 13:56
Duplicate of #190

**Closed by LordGolias** 2018-10-13 13:56 UTC
